//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba20v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tov
    {
        public int ID { get; set; }
        public string demensions { get; set; }
        public string composition { get; set; }
        public Nullable<int> price1 { get; set; }
        public Nullable<int> price2 { get; set; }
        public Nullable<int> price3 { get; set; }
        public string box { get; set; }
        public Nullable<int> price4 { get; set; }
        public string description { get; set; }
        public Nullable<int> id_postav { get; set; }
        public Nullable<int> id_nom { get; set; }
    
        public virtual nom nom { get; set; }
        public virtual Postav Postav { get; set; }
    }
}
